version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: agrt
      MYSQL_DATABASE: feedmill_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - .mysql_data:/var/lib/mysql
      - ./sql_great_table.sql:/docker-entrypoint-initdb.d/1.sql
      - ./sql_insert_testdata.sql:/docker-entrypoint-initdb.d/2.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: agrt

  fastapi:
    build: .
    container_name: fastapi-app
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DB: feedmill_db
    ports:
      - "8000:8000"

