services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: agrt
      MYSQL_DATABASE: feedmill_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sql_great_table.sql:/docker-entrypoint-initdb.d/1.sql         # создание таблиц СРАБАТЫВАЕТ ТОЛЬКО ПРИ ПЕРВОМ ЗАПУСКЕ
      - ./sql_insert_testdata.sql:/docker-entrypoint-initdb.d/2.sql     # наполнение тестовыми данными
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: agrt

# разкоментировать для полного докера
#services:
#  web:
#    image: nginx
#  fastapi:
#    build: .
#    container_name: fastapi-app
#    restart: always
#    depends_on:
#      - db
#    environment:
#      MYSQL_HOST: db
#      MYSQL_USER: myuser
#      MYSQL_PASSWORD: mypassword
#      MYSQL_DB: feedmill_db
#      # Можно добавить еще переменные для секретного ключа и пр.
#    ports:
#      - "8000:8000"
##    volumes:
##     - .:/app
